<?php
// $Id: luceneapi_test.install,v 1.1.2.1 2009/09/17 01:21:16 cpliakas Exp $

/**
 * @file
 * Installation functions for the Search Lucene Test module.
 *
 * @ingroup luceneapi
 */

/**
 * Implementation of hook_uninstall().
 */
function luceneapi_test_uninstall() {

  // clears all cached luceneapi_test search results
  if (db_table_exists('cache_luceneapi')) {
    cache_clear_all('luceneapi_test', 'cache_luceneapi', TRUE);
  }

  // deletes index directory
  $index_path = variable_get(
    'luceneapi_test:index_path',
    file_directory_path() . DIRECTORY_SEPARATOR .'luceneapi_test'
  );
  if (is_dir($index_path)) {
    $nomask = array('RCS', 'SCCS', 'CVS', 'CVS.adm', 'RCSLOG', 'tags', 'TAGS', '.git', '.bzr');
    $files = file_scan_directory($index_path, '.*', $nomask);
    foreach ($files as $file) {
      @unlink($file->filename);
    }
    @unlink(sprintf('%s/.htaccess', $index_path));
    @rmdir($index_path);
  }

  // removes all variables that start with "luceneapi_test:"
  $result = db_query("SELECT name FROM {variable} WHERE name LIKE 'luceneapi_test:%%'");
  while ($row = db_fetch_object($result)) {
    variable_del($row->name);
  }
}

/**
 * Implementation of hook_requirements().
 */
function luceneapi_test_requirements($phase) {
  // Ensure translations don't break at install time
  $t = get_t();

  // if requirements fail for Search Lucene API, this module will still get
  // installed breaking the site.  This code double checks the requirements to
  // get around this bug.  Requirements are only returned on failure.
  if ('install' == $phase) {

    // bails if Drupal is in the process of being installed
    $function = 'install_verify_drupal';
    if (function_exists($function) && !$function()) {
      return array();
    }

    // makes sure path to luceneapi exists
    if (!$luceneapi_path = drupal_get_path('module', 'luceneapi')) {
      return array(
        'luceneapi_test' => array(
          'title' => t('Search Lucene Test'),
          'severity' => REQUIREMENT_ERROR,
          'description' => t('Search Lucene API not installed.'),
        ),
      );
    }

    // formats path to library directory, tests PHP version
    $lib_dir = sprintf('%s/lib', $luceneapi_path);
    $php_ok = version_compare(PHP_VERSION, '5.1.6', '>=');
    if (!is_dir("$lib_dir/Zend") || !is_dir("$lib_dir/LuceneAPI") || !$php_ok) {
      return array(
        'luceneapi_test' => array(
          'title' => t('Search Lucene Test'),
          'severity' => REQUIREMENT_ERROR,
          'description' => t(
            'Search Lucene Test depends on Search Lucene API.'),
        ),
      );
    }
  }
}
