<?php
// $Id: luceneapi.exception.inc,v 1.1.2.3 2009/12/01 00:35:48 cpliakas Exp $

/**
 * @file
 * Defines the LuceneAPI_Exception class in cases where the Zend Framework
 * components are unavailable.  DO NOT source this file unless you are positive
 * the LuceneAPI_Exception class is unavailable.
 *
 * @ingroup luceneapi
 */

/**
 * The LuceneAPI_Exception class.
 */
class LuceneAPI_Exception extends Exception {
}
