<?php
/**
* @file drupal module file implementing bluff charting
*/

/**
* Implementation of hook_charts_graphs_provider 
**/
function charts_bluff_chartgraph_provider() {
  
  $provider =  array(
    'path' => dirname(__FILE__) . '/charts_bluff.class.inc', //must be full path
    'clazz' => 'ChartsBluff', //implementation class' name
    'name' => 'bluff', //name used when invoking through a factroy method
    'nice_name' => 'Charts: Bluff',
    'chart_types' => array(
      'line' => t('Line'),
      'bar' => t('Bar'), 
      'pie' => t('Pie'),           
      'area' => t('Area'),
      'sidebar' => t('Sidebar'),
      'side_stacked_bar' => t('Side Stackedbar'),
      'stacked_area' => t('Stacked Area'),
      'stacked_bar' => t('Stacked Bar')
    ),
  );    
  
  return (object) $provider;
  
}