<?php
// $Id: luceneapi_node.api.inc,v 1.1.2.3 2009/10/24 20:09:24 cpliakas Exp $

/**
 * @file
 * Example file that defines the Search Lucene Node hooks.
 *
 * @ingroup luceneapi
 */

/**
 * Defines fields that have configurable bias settings.
 *
 * @return
 *   An array of fields.
 */
function hook_luceneapi_node_bias_fields() {
}

/**
 * Defines HTML tags that have configurable bias settings.
 *
 * @return
 *   An array of tags.
 */
function hook_luceneapi_node_bias_tags() {
}
